// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qrlhvyzjfdevcnjjqmaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFybGh2eXpqZmRldmNuampxbWF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzMzMTUsImV4cCI6MjA2OTkwOTMxNX0.Kf-hGtYXbYCcIcO9ggoMCBgBbs9bvgFoLH0rQplRsT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);